[Rainmeter]
Update=1000

[MeasureTime]
Measure=Time
Format="%#I:%M"

[MeasureDate]
Measure=Time
Format=%#d

[MeasureMonth]
Measure=Time
Format=%B
Substitute="January":"JAN.","February":"FEB.","March":"MAR.","April":"APR.","May":"MAY.","June":"JUN.","July":"JUL.","August":"AUG.","September":"SEP.","October":"OCT.","November":"NOV.","December":"DEC."

[MeasureDay1]
Measure=Time
Format=%A
Substitute="Monday":"MON","Tuesday":"TUES","Wednesday":"WED","Thursday":"THURS","Friday":"FRI","Saturday":"SAT","Sunday":"SUN"

[Background]
Meter=IMAGE
SolidColor=0,0,0,1
X=0
Y=0
W=200
H=110

[MeterTime]
FontFace=8BIT WONDER
MeasureName=MeasureTime
Meter=STRING
X=4
Y=0
FontColor=233, 196, 106
FontSize=40
FontFace=8BIT WONDER
StringAlign=Left
StringStyle=Bold
AntiAlias=1
;Text="12:00"
MouseOverAction=[Play "#@#Sounds\timenavigate.wav"][!SetOption MeasureTime Format "%H:%M"][!UpdateMeasure MeasureTime][!UpdateMeter *][!Redraw]
MouseLeaveAction=[Play "#@#Sounds\timenavigate.wav"][!SetOption MeasureTime Format "%#I:%M"][!UpdateMeasure MeasureTime][!UpdateMeter *][!Redraw]

[MeterMonth]
FontFace=8BIT WONDER
MeasureName=MeasureMonth
Meter=STRING
W=200
X=5r
Y=68r
FontColor=244, 162, 97
FontSize=20
FontFace=#LocalFontFace#
StringAlign=Left
;StringStyle=Normal
AntiAlias=1

[MeterDate]
FontFace=8BIT WONDER
MeasureName=MeasureDate
Meter=STRING
X=112
Y=2r
FontColor=244, 162, 97
FontSize=20
FontFace=#LocalFontFace#
StringAlign=LEft
;StringStyle=Normal
AntiAlias=1

[MeterDay1]
FontFace=8BIT WONDER
MeasureName=MeasureDay1
Meter=STRING
X=-102r
Y=38r
FontColor=231, 111, 81
FontSize=17
FontFace=#LocalFontFace#
StringAlign=Left
StringStyle=Bold
AntiAlias=1
